apiVersion: v1
kind: Service
metadata:
  name:  mlapp-service
spec:
  selector:
    app:  mlapp
  type:  NodePort
  ports:
  - name:  mlapp-flask
    port:  5000
    nodePort: 30950
    targetPort:  5000
#  type: NodePort